import fs from 'node:fs';import {projectStore} from './src/services/ProjectStore';
const file='game-server/public/projects/GCS-CMS.json',p=JSON.parse(fs.readFileSync(file,'utf8'));fs.copyFileSync(file,'backups/GCS-CMS-before-variable-notes-'+Date.now()+'.json');projectStore.setProject(p);
const common:any={Token:'Sitzungskennung des angemeldeten Spielers. Wird bei CMS-Anfragen zur Identifikation mitgesendet und beim Abmelden gelöscht; kein Passwort.',Modus:'Aktuelle Spieleransicht: login, rooms, games oder profile. Steuert die Auswahlabläufe zwischen Einwahl, Galerie und Profil.',Busy:'Gemeinsame Eingabesperre: 1 während einer laufenden Benutzeranfrage, 0 wenn die nächste Eingabe erlaubt ist.',isProjectChangeAvailable:'Interne Änderungsmarkierung des GCS-Editors; kennzeichnet ungespeicherte Projektänderungen.',EinwahlHaus:'ID des Hauses, in dem der Emoji-Code geprüft wird. Kann beim Browser-Einstieg über den Parameter house vorgegeben werden.',Anzahl:'Anzahl der bisher gewählten Emoji-Bilder (0 bis 4). Die Anmeldung benötigt vier Bilder.',Auswahl:'ID des zuletzt angeklickten Listeneintrags; wird vom Auswahl-Task entsprechend der aktuellen Ansicht weiterverarbeitet.',Raum:'ID des ausgewählten Raumes für Spielefreigaben, Mitgliedschaften oder Spielstart.',SpielURL:'Vom Server freigegebener /play/-Link für das ausgewählte Spiel. Der Spiel-Host öffnet ihn und leert anschließend die Variable.',Seite:'Index der angezeigten Listenseite, beginnend bei 0. Wird bei Vorher/Weiter geändert und an den Server gesendet.',Seiten:'Vom Server gelieferte Gesamtzahl der Listenseiten; begrenzt das Vor- und Zurückblättern.',EingabenGueltig:'Ergebnis der lokalen Prüfung, ob Benutzername und Passwort eingegeben wurden. Ersetzt nicht die Passwortprüfung auf dem Server.',VerwaltungsModus:'Aktuelle Verwaltungs-Liste; bestimmt den API-Endpunkt und die Bedeutung der ausgewählten Karten.',Haus:'ID des ausgewählten Hauses; begrenzt Haus- und Zuständigkeitsaktionen auf diesen Kontext.',HausName:'Anzeigename des ausgewählten Hauses für Kontextanzeige und Bearbeitungsfelder.',RaumName:'Anzeigename des ausgewählten Raumes für die Kontextanzeige und das Bearbeitungsfeld.',RaumAktiv:'Aktivierungszustand des ausgewählten Raumes; Ausgangswert beim Aktivieren oder Deaktivieren.',Person:'ID der ausgewählten Person, deren Admin-Zuständigkeit bearbeitet wird.',AuswahlName:'Anzeigename des angeklickten Eintrags; wird zusammen mit dessen ID in den Bearbeitungskontext übernommen.',Ziel:'Arbeitswert für den Aktivierungszustand: bei Auswahl zunächst aktueller Zustand, beim Umschalten der gewünschte neue Zustand für die Serveranfrage.',SpielId:'ID des ausgewählten eigenen Spiels. Wird für Veröffentlichen/Zurückziehen verwendet und nach einem Upload auf das neue Spiel gesetzt.'};
let count=0;for(const stage of p.stages)for(const v of [...stage.variables||[],...(stage.objects||[]).filter((o:any)=>o.isVariable)]){
 let note=common[v.name];const index=v.name.match(/^(Code|Slot|Next|Name|Active)([0-3])$/);
 if(index){const position=Number(index[2])+1;note=({Code:`Interne Emoji-ID an Position ${position} des vierteiligen Anmeldecodes (z. B. cat); kein angezeigtes Emoji-Zeichen.`,Slot:`ID des Eintrags auf Karte ${position} der aktuellen Listenseite. Wird beim Anklicken nach Auswahl bzw. SpielId übernommen.`,Next:`Vom Server berechneter nächster Aktivierungszustand für Karte ${position}; wird beim Umschalten einer Freigabe oder Mitgliedschaft verwendet.`,Name:`Anzeigename des Eintrags auf Karte ${position}; wird bei Auswahl nach AuswahlName übernommen.`,Active:`Aktueller Aktivierungs- bzw. Zuweisungszustand des Eintrags auf Karte ${position}; Ausgangswert für eine bestätigte Änderung.`} as any)[index[1]];}
 if(stage.id==='stage_admin'&&v.name==='Ziel')note='Gewünschter neuer Zustand einer Spielefreigabe oder Mitgliedschaft; wird aus Next0–Next3 übernommen und als active an den Server gesendet.';
 if(stage.id==='stage_super'&&['Raum','RaumName','RaumAktiv'].includes(v.name))note=({Raum:'Arbeits-ID des ausgewählten Hauses für den übernommenen Bearbeitungsablauf; enthält hier eine Haus-ID, keine Raum-ID.',RaumName:'Arbeitsname des ausgewählten Hauses für dessen Bearbeitung; der Variablenname stammt aus dem gemeinsamen Verwaltungsablauf.',RaumAktiv:'Aktivierungszustand des ausgewählten Hauses; Ausgangswert beim Aktivieren oder Deaktivieren.'} as any)[v.name];
 if(stage.id==='stage_super'&&v.name==='Person')note='ID der ausgewählten Person für HouseAdmin-Zuweisung und Einladung zur Einrichtung eines Verwaltungszugangs.';
 if(!note)throw Error('Zweck fehlt: '+stage.id+'/'+v.name);
 projectStore.dispatch({type:'SET_PROPERTY',target:v,path:'description',value:note});count++;
}
fs.writeFileSync(file,JSON.stringify(p,null,2));console.log(count+' CMS-Variablen dokumentiert.');
