import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import prettierConfig from 'eslint-config-prettier';

/** @type {import('eslint').Linter.Config[]} */
export default [
  // Ignores
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'release/**',
      'src-tauri/**',
      'game-server/node_modules/**',
      '*.config.js',
      '*.config.ts',
    ],
  },

  // Base JS/TS Config
  js.configs.recommended,

  // TypeScript
  {
    files: ['src/**/*.ts', 'tests/**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: process.cwd(),
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        HTMLElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLVideoElement: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        DragEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        CustomEvent: 'readonly',
        Node: 'readonly',
        Element: 'readonly',
        Document: 'readonly',
        Window: 'readonly',
        Storage: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        // Browser APIs
        crypto: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        indexedDB: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        screen: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        // Jest/Test globals
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        Promise: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        Symbol: 'readonly',
        Intl: 'readonly',
        Buffer: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        global: 'readonly',
        GLOBAL: 'readonly',
        root: 'readonly',
        WebSocket: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        ReadableStream: 'readonly',
        WritableStream: 'readonly',
        TransformStream: 'readonly',
        Headers: 'readonly',
        WebAssembly: 'readonly',
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly',
        BigInt: 'readonly',
        BigInt64Array: 'readonly',
        BigUint64Array: 'readonly',
        DataView: 'readonly',
        ArrayBuffer: 'readonly',
        Uint8Array: 'readonly',
        Uint16Array: 'readonly',
        Uint32Array: 'readonly',
        Int8Array: 'readonly',
        Int16Array: 'readonly',
        Int32Array: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        ImageData: 'readonly',
        ImageBitmap: 'readonly',
        OffscreenCanvas: 'readonly',
        Path2D: 'readonly',
        TextMetrics: 'readonly',
        CanvasGradient: 'readonly',
        CanvasPattern: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        XMLDocument: 'readonly',
        XPathEvaluator: 'readonly',
        XPathResult: 'readonly',
        XSLTProcessor: 'readonly',
        DOMImplementation: 'readonly',
        DocumentType: 'readonly',
        DocumentFragment: 'readonly',
        ShadowRoot: 'readonly',
        Template: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLSlotElement: 'readonly',
        MediaQueryList: 'readonly',
        Screen: 'readonly',
        ScreenOrientation: 'readonly',
        VisualViewport: 'readonly',
        DeviceOrientationEvent: 'readonly',
        DeviceMotionEvent: 'readonly',
        Geolocation: 'readonly',
        GeolocationPosition: 'readonly',
        GeolocationCoordinates: 'readonly',
        Notification: 'readonly',
        Permissions: 'readonly',
        PermissionStatus: 'readonly',
        BroadcastChannel: 'readonly',
        MessageChannel: 'readonly',
        MessagePort: 'readonly',
        Worker: 'readonly',
        SharedWorker: 'readonly',
        DedicatedWorkerGlobalScope: 'readonly',
        ServiceWorker: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        ServiceWorkerContainer: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        FileSystem: 'readonly',
        FileSystemEntry: 'readonly',
        FileSystemDirectoryEntry: 'readonly',
        FileSystemFileEntry: 'readonly',
        FileSystemDirectoryReader: 'readonly',
        FileWriter: 'readonly',
        FileSystemFlags: 'readonly',
        IObserver: 'readonly',
        Iterator: 'readonly',
        AsyncIterator: 'readonly',
        Generator: 'readonly',
        AsyncGenerator: 'readonly',
        AggregateError: 'readonly',
        FinalizationRegistry: 'readonly',
        WeakRef: 'readonly',
        Compat: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      // Graduell anzugehen:
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'error',
      '@typescript-eslint/no-unused-vars': 'warn',
      // Stilistische/syntaktische Warnungen:
      'no-case-declarations': 'warn',
      '@typescript-eslint/no-this-alias': 'warn',
      '@typescript-eslint/no-unsafe-function-type': 'warn',
      'no-empty': 'warn',
      'no-useless-escape': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      'no-prototype-builtins': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      // Kritische Sicherheitsregeln (Error):
      'no-debugger': 'error',
      'no-alert': 'off',  // wir nutzen custom Dialogs
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
    },
  },

  // Test-Dateien: console.* erlaubt (Test-Reporting)
  {
    files: ['src/**/*.test.ts', 'tests/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },

  // Prettier (muss zuletzt)
  prettierConfig,
];
