import { GameProject } from '../model/types';

/**
 * Runtime version for exported games.
 * Increment this when making breaking changes to the runtime.
 * Format: MAJOR.MINOR.PATCH
 */
export const RUNTIME_VERSION = '1.0.0';

/**
 * GameExporter - Generates a standalone HTML or JSON game from a GameProject
 */
export class GameExporter {

    /**
     * Export the project as a standalone HTML file
     */
    async exportHTML(project: GameProject): Promise<void> {
        // 1. Fetch the actual runtime bundle generated by Vite
        let runtimeCode = '';
        try {
            const resp = await fetch('/runtime-standalone.js');
            if (resp.ok) {
                const code = await resp.text();
                // Safety check: If Vite returns HTML (e.g. 404 page), don't embed it!
                if (code.trim().startsWith('<!DOCTYPE') || code.trim().startsWith('<html')) {
                    console.error('GameExporter: Fetched runtime-standalone.js but got HTML instead of JS. Bundle might be missing.');
                    runtimeCode = '';
                } else {
                    runtimeCode = code;
                }
            } else {
                console.warn(`GameExporter: Could not fetch /runtime-standalone.js (Status: ${resp.status}). Export will lack logic.`);
            }
        } catch (e) {
            console.error('GameExporter: Network error fetching runtime bundle:', e);
        }

        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64 for a truly standalone file
        try {
            await this.embedImages(cleanedProject);
        } catch (e) {
            console.warn('GameExporter: Error embedding images:', e);
        }

        const html = this.generateStandaloneHTML(cleanedProject, runtimeCode);
        await this.downloadFile(html, `${project.meta.name.replace(/\s+/g, '_')}.html`, 'text/html');
    }

    /**
     * Export the project as a clean JSON file (without editor/flow info)
     */
    async exportJSON(project: GameProject): Promise<void> {
        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64 for a truly standalone project file
        try {
            await this.embedImages(cleanedProject);
        } catch (e) {
            console.warn('GameExporter: Error embedding images in JSON:', e);
        }

        const json = JSON.stringify(cleanedProject, null, 2);
        await this.downloadFile(json, `${project.meta.name.replace(/\s+/g, '_')}.json`, 'application/json');
    }

    /**
     * Legacy method for backward compatibility
     */
    async export(project: GameProject): Promise<void> {
        return this.exportHTML(project);
    }

    /**
     * Removes all editor-only properties (flow editor, node positions, etc.)
     * to keep the game file small and clean for the platform.
     */
    private getCleanProject(project: GameProject): any {
        // Deep clone to avoid modifying original project
        const clean = JSON.parse(JSON.stringify(project));

        // 1. Remove Flow Editor data (both new and legacy)
        delete clean.flow;
        delete clean.flowCharts;

        // 2. Clean any remaining legacy flowGraph from Tasks
        if (clean.tasks) {
            clean.tasks.forEach((task: any) => {
                delete task.flowGraph;
            });
        }

        // 3. Add meta info for platform
        if (!clean.meta) clean.meta = {};
        clean.meta.exportedAt = new Date().toISOString();
        clean.meta.type = 'standalone_game';
        clean.meta.runtimeVersion = RUNTIME_VERSION;

        return clean;
    }

    /**
     * Generate a complete standalone HTML file with embedded runtime
     */
    private generateStandaloneHTML(project: any, runtimeJS: string): string {
        const projectJSON = JSON.stringify(project, null, 2);
        const gridConfig = project.stage.grid;
        const stageWidth = gridConfig.cols * gridConfig.cellSize;
        const stageHeight = gridConfig.rows * gridConfig.cellSize;

        return `<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${this.escapeHtml(project.meta.name)}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden;
            background: #0f172a;
        }
        body {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        }
        #stage-container {
            position: relative;
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }
        #stage {
            position: relative;
            width: ${stageWidth}px;
            height: ${stageHeight}px;
            background: ${gridConfig.backgroundColor || '#ffffff'};
            box-shadow: 0 20px 50px rgba(0,0,0,0.5);
            border-radius: 4px;
            overflow: hidden;
            transform-origin: center center;
            flex-shrink: 0;
        }
        .game-object {
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            box-sizing: border-box;
            overflow: hidden;
            user-select: none;
        }
    </style>
</head>
<body>
    <div id="stage-container">
        <div id="stage"></div>
    </div>
    
    <script>
    // ═══════════════════════════════════════════════════════════════
    // Standalone Runtime Bundle (Shared Logic)
    // ═══════════════════════════════════════════════════════════════
    ${runtimeJS}

    // ═══════════════════════════════════════════════════════════════
    // Start Game
    // ═══════════════════════════════════════════════════════════════
    window.PROJECT = ${projectJSON};
    
    document.addEventListener('DOMContentLoaded', () => {
        if (typeof window.startStandalone === 'function') {
            window.startStandalone(window.PROJECT);
        } else {
            console.error('Standalone Runtime not found! Check if runtime-standalone.js was bundled correctly.');
            document.body.innerHTML = '<h2 style="color:white;text-align:center;margin-top:20%">Error: Runtime not found.</h2>';
        }
    });
    </script>
</body>
</html>`;
    }

    /**
     * Finds and embeds all image references in the project as Base64 Data URLs.
     */
    private async embedImages(project: any): Promise<void> {
        const imageRefs = new Map<string, string>(); // path -> dataUrl

        // 1. Collect all unique image paths from the project recursively
        const collectPaths = (obj: any) => {
            if (!obj || typeof obj !== 'object') return;

            // Common image properties
            const props = ['backgroundImage', 'src', 'icon'];
            props.forEach(p => {
                const val = obj[p];
                if (val && typeof val === 'string' && val.length > 0 && !val.startsWith('data:') && !val.startsWith('http')) {
                    imageRefs.set(val, '');
                }
            });

            // Recurse into all properties (handles objects[], stage, grid, etc.)
            Object.values(obj).forEach(val => {
                if (Array.isArray(val)) {
                    val.forEach(collectPaths);
                } else if (val && typeof val === 'object') {
                    // Avoid recursing into some known non-component fields if needed, 
                    // but for JSON it's safe to just go deep.
                    collectPaths(val);
                }
            });
        };

        collectPaths(project);

        // 2. Fetch and convert to Base64
        console.log(`[GameExporter] Found ${imageRefs.size} unique images to embed.`);
        for (const [path, _] of imageRefs) {
            try {
                // Try absolute path first, then relative to images/
                let fullPath = path;
                if (!path.startsWith('/')) {
                    fullPath = `/images/${path}`;
                }

                console.log(`[GameExporter] Fetching image: ${fullPath}`);
                const resp = await fetch(fullPath);
                if (resp.ok) {
                    const blob = await resp.blob();
                    const dataUrl = await this.blobToDataUrl(blob);
                    imageRefs.set(path, dataUrl);
                    console.log(`[GameExporter] Successfully embedded: ${path}`);
                } else {
                    console.warn(`[GameExporter] Failed to fetch image: ${fullPath} (Status: ${resp.status})`);
                }
            } catch (e) {
                console.warn(`[GameExporter] Network error embedding image: ${path}`, e);
            }
        }

        // 3. Replace paths with Data URLs in the project recursively
        const replacePaths = (obj: any) => {
            if (!obj || typeof obj !== 'object') return;

            const props = ['backgroundImage', 'src', 'icon'];
            props.forEach(p => {
                const val = obj[p];
                if (val && typeof val === 'string' && imageRefs.has(val)) {
                    const dataUrl = imageRefs.get(val);
                    if (dataUrl) obj[p] = dataUrl;
                }
            });

            Object.values(obj).forEach(val => {
                if (Array.isArray(val)) {
                    val.forEach(replacePaths);
                } else if (val && typeof val === 'object') {
                    replacePaths(val);
                }
            });
        };

        replacePaths(project);
    }

    /**
     * Convert a Blob to a Base64 Data URL
     */
    private blobToDataUrl(blob: Blob): Promise<string> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    }

    /**
     * Escape HTML special characters
     */
    private escapeHtml(text: string): string {
        const map: Record<string, string> = {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#039;'
        };
        return text.replace(/[&<>"']/g, m => map[m]);
    }

    /**
     * Trigger file download with File System Access API
     */
    private async downloadFile(content: string, filename: string, mimeType: string): Promise<void> {
        // Try File System Access API (modern browsers)
        if ('showSaveFilePicker' in window) {
            try {
                const handle = await (window as any).showSaveFilePicker({
                    suggestedName: filename,
                    types: [{
                        description: mimeType === 'text/html' ? 'HTML Game File' : 'JSON Game File',
                        accept: { [mimeType]: [mimeType === 'text/html' ? '.html' : '.json'] }
                    }]
                });
                const writable = await handle.createWritable();
                await writable.write(content);
                await writable.close();
                alert(`Game exported successfully!\n\nFile: ${handle.name}\n\nOpen it in any browser to play.`);
                return;
            } catch (err: any) {
                // User cancelled or error - fall through to legacy method
                if (err.name === 'AbortError') return;
                console.warn('File System Access API failed, using fallback:', err);
            }
        }

        // Fallback for browsers without File System Access API
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        setTimeout(() => document.body.removeChild(a), 2000);
        alert(`Game exported to Downloads folder.\n\nFile: ${filename}`);
    }
}
