import { GameProject } from '../model/types';
import { gzipSync, zipSync } from 'fflate';
import { Logger } from '../utils/Logger';
import { NotificationToast } from '../editor/ui/NotificationToast';
import { SecurityUtils } from '../utils/SecurityUtils';
import { RUNTIME_VERSION } from '../utils/RuntimeVersion';
import { network } from '../multiplayer';
export { RUNTIME_VERSION };

const logger = Logger.get('GameExporter', 'Export_System');

/**
 * GameExporter - Generates a standalone HTML or JSON game from a GameProject
 * Supports both plain and gzip-compressed exports.
 */
export class GameExporter {

    /**
     * Export the project as a standalone HTML file
     */
    async exportHTML(project: GameProject): Promise<void> {
        // 1. Fetch the actual runtime bundle generated by Vite
        let runtimeCode = '';
        try {
            // First attempt: Fetch via HTTP (works in Web, Vite Dev Server, and Tauri)
            try {
                const resp = await fetch('runtime-standalone.js');
                if (resp.ok) {
                    const code = await resp.text();
                    // Safety check: If Vite returns HTML (e.g. 404 page), don't embed it!
                    if (!code.trim().startsWith('<!DOCTYPE') && !code.trim().startsWith('<html')) {
                        runtimeCode = code;
                    }
                }
            } catch (fetchErr) {
                logger.warn('GameExporter: Fetch failed, falling back to FS...', fetchErr);
            }

            // Fallback for Electron offline (file://) where fetch might be blocked
            if (!runtimeCode && (window as any).electronFS && !(window as any).__TAURI_INTERNALS__) {
                const appPath = await (window as any).electronFS.getAppPath();
                try {
                    // In production (app.asar), Vite copies public -> dist
                    runtimeCode = await (window as any).electronFS.readFile(`${appPath}/dist/runtime-standalone.js`);
                } catch {
                    // In development, it's still in public/
                    runtimeCode = await (window as any).electronFS.readFile(`${appPath}/public/runtime-standalone.js`);
                }
            }
        } catch (e) {
            logger.error('GameExporter: Network/FS error fetching runtime bundle:', e);
        }

        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64 for a truly standalone file
        try {
            await this.embedMedia(cleanedProject);
        } catch (e) {
            logger.warn('GameExporter: Error embedding images:', e);
        }

        const html = this.generateStandaloneHTML(cleanedProject, runtimeCode);
        await this.downloadFile(html, `${project.meta.name.replace(/\s+/g, '_')}.html`, 'text/html');
    }

    /**
     * Export the project as a clean JSON file (without editor/flow info)
     */
    async exportJSON(project: GameProject): Promise<void> {
        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64 for a truly standalone project file
        try {
            await this.embedMedia(cleanedProject);
        } catch (e) {
            logger.warn('GameExporter: Error embedding images in JSON:', e);
        }

        const json = JSON.stringify(cleanedProject, null, 2);
        await this.downloadFile(json, `${project.meta.name.replace(/\s+/g, '_')}.json`, 'application/json');
    }

    /**
     * Legacy method for backward compatibility
     */
    async export(project: GameProject): Promise<void> {
        return this.exportHTML(project);
    }

    /**
     * Export the project as a gzip-compressed standalone HTML file
     */
    async exportHTMLCompressed(project: GameProject): Promise<void> {
        // 1. Fetch the actual runtime bundle
        let runtimeCode = '';
        try {
            try {
                const resp = await fetch('runtime-standalone.js');
                if (resp.ok) {
                    const code = await resp.text();
                    if (!code.trim().startsWith('<!DOCTYPE') && !code.trim().startsWith('<html')) {
                        runtimeCode = code;
                    }
                }
            } catch (fetchErr) {
                logger.warn('GameExporter: Fetch compressed failed, falling back to FS...', fetchErr);
            }

            if (!runtimeCode && (window as any).electronFS && !(window as any).__TAURI_INTERNALS__) {
                const appPath = await (window as any).electronFS.getAppPath();
                try {
                    runtimeCode = await (window as any).electronFS.readFile(`${appPath}/dist/runtime-standalone.js`);
                } catch {
                    runtimeCode = await (window as any).electronFS.readFile(`${appPath}/public/runtime-standalone.js`);
                }
            }
        } catch (e) {
            logger.error('GameExporter: Network/FS error fetching runtime bundle:', e);
        }

        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64
        try {
            await this.embedMedia(cleanedProject);
        } catch (e) {
            logger.warn('GameExporter: Error embedding images:', e);
        }

        const html = this.generateCompressedHTML(cleanedProject, runtimeCode);
        await this.downloadFile(html, `${project.meta.name.replace(/\s+/g, '_')}_compressed.html`, 'text/html');
    }

    /**
     * Export the project as a gzip-compressed JSON file
     */
    async exportJSONCompressed(project: GameProject): Promise<void> {
        const cleanedProject = this.getCleanProject(project);

        // Embed images as Base64
        try {
            await this.embedMedia(cleanedProject);
        } catch (e) {
            logger.warn('GameExporter: Error embedding images in JSON:', e);
        }

        // Mark as compressed and add the compressed data
        const compressedData = this.compressProject(cleanedProject);
        const wrapper = {
            _compressed: true,
            _version: RUNTIME_VERSION,
            data: compressedData
        };

        const json = JSON.stringify(wrapper, null, 2);
        await this.downloadFile(json, `${project.meta.name.replace(/\s+/g, '_')}_compressed.json`, 'application/json');
    }

    /**
     * Export the project as a Node.js server bundle (ZIP)
     */
    async exportServerBundle(project: GameProject): Promise<void> {
        // 1. Fetch runtime
        let runtimeCode = '';
        try {
            const runtimeUrl = new URL('runtime-standalone.js', window.location.href).href;
            const resp = await fetch(runtimeUrl);
            if (resp.ok) {
                runtimeCode = await resp.text();
            }
        } catch (e) {
            logger.error('GameExporter: Error fetching runtime:', e);
        }

        const cleanedProject = this.getCleanProject(project);
        const projectName = project.meta.name.replace(/\s+/g, '_');

        // 2. Prepare files for ZIP
        const files: Record<string, Uint8Array> = {};
        const encoder = new TextEncoder();

        files['project.json'] = encoder.encode(JSON.stringify(cleanedProject, null, 2));
        files['runtime.js'] = encoder.encode(runtimeCode);
        files['server.js'] = encoder.encode(this.generateServerJS());
        files['package.json'] = encoder.encode(this.generateServerPackageJSON(projectName));
        files['Dockerfile'] = encoder.encode(this.generateDockerfile());
        files['fly.toml'] = encoder.encode(this.generateFlyToml(projectName));

        // Add Headless Runtime files (this is a bit tricky as they are TS, but for the bundle 
        // we might want to include them or assume they are part of the runtime.js)
        // Since runtime.js is bundled, it should ideally include everything.
        // But for clarity, we provide a generic server.js that imports from the bundle.

        // 3. Create ZIP
        const zipped = zipSync(files);

        // 4. Download
        const blob = new Blob([zipped.buffer as ArrayBuffer], { type: 'application/zip' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${projectName}_server_bundle.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);

        NotificationToast.show(`Server-Bundle exportiert: ${projectName}_server_bundle.zip\n\nEnthält Dockerfile und fly.toml für das Deployment.`);
    }

    private generateServerJS(): string {
        return `
/**
 * GCS Standalone Server Entry
 * Lädt die GCS Engine (IIFE) und startet die Headless Runtime.
 */
require('./runtime.js'); 
const project = require('./project.json');

// HeadlessRuntime und HeadlessServer sind durch das IIFE-Bundle global verfügbar
const runtime = new HeadlessRuntime(project);
const server = new HeadlessServer(runtime);

logger.info('--- GCS Headless Server Start ---');
server.start();
`;
    }

    private generateServerPackageJSON(name: string): string {
        return JSON.stringify({
            name: name.toLowerCase(),
            version: "1.0.0",
            description: "GCS Exported Backend",
            main: "server.js",
            dependencies: {
                "express": "^4.18.2",
                "fflate": "^0.8.2"
            },
            scripts: {
                "start": "node server.js"
            }
        }, null, 2);
    }

    private generateDockerfile(): string {
        return `
FROM node:18-slim
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
`;
    }

    private generateFlyToml(name: string): string {
        return `
app = "${name.toLowerCase()}"
primary_region = "fra"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
`;
    }

    /**
     * Compress project JSON using gzip and encode as Base64
     */
    private compressProject(project: any): string {
        const json = JSON.stringify(project);
        const compressed = gzipSync(new TextEncoder().encode(json));
        // Convert Uint8Array to Base64
        let binary = '';
        for (let i = 0; i < compressed.length; i++) {
            binary += String.fromCharCode(compressed[i]);
        }
        return btoa(binary);
    }

    /** Helfer zum sicheren Serialisieren von Objekten mit zirkulären Referenzen (z.B. Editor-Instanzen) */
    private safeStringify(obj: any): string {
        const seen = new WeakSet();
        const SKIP_KEYS = new Set(['renderer', 'host', 'parent', 'stage', 'editor', '__rawSource', '_listeners', '_eventTarget']);
        return JSON.stringify(obj, (key: string, value: any) => {
            if (SKIP_KEYS.has(key)) return undefined;
            if (typeof value === 'object' && value !== null) {
                if (seen.has(value)) return undefined;
                seen.add(value);
            }
            return value;
        });
    }

    /**
     * Removes all editor-only properties (flow editor, node positions, etc.)
     * to keep the game file small and clean for the platform.
     */
    public getCleanProject(project: GameProject): any {
        // 1. Whitelist for top-level keys
        const whitelist = ['meta', 'stages', 'activeStageId', 'variables', 'tasks', 'actions', 'stage', 'objects', 'flowCharts', 'splashAutoHide', 'splashDuration', 'themes', 'activeThemeId'];

        const clean: any = {};
        whitelist.forEach(key => {
            if ((project as any)[key] !== undefined) {
                // Nutze safeStringify, um TypeError bei zirkulären Laufzeit-Referenzen (parent, editor) zu verhindern
                clean[key] = JSON.parse(this.safeStringify((project as any)[key]));
            }
        });

        // 2. Recursive deep clean
        this.deepClean(clean);

        // 3. Specialized cleaning for Stages
        if (clean.stages) {
            // Variables are kept in objects intentionally.
        }

        // 4. Add meta info for platform
        if (!clean.meta) clean.meta = {};
        const mainStage = clean.stages?.find((s: any) => s.type === 'main');
        if (mainStage) {
            if (mainStage.gameName) clean.meta.name = mainStage.gameName;
            if (mainStage.author) clean.meta.author = mainStage.author;
            if (mainStage.description) clean.meta.description = mainStage.description;
        }

        clean.meta.exportedAt = new Date().toISOString();
        clean.meta.type = 'standalone_game';
        clean.meta.runtimeVersion = RUNTIME_VERSION;

        return clean;
    }

    /**
     * Recursively removes internal properties and editor-only noise
     */
    private deepClean(obj: any): void {
        if (!obj || typeof obj !== 'object') return;

        if (Array.isArray(obj)) {
            obj.forEach(item => this.deepClean(item));
            return;
        }

        // ACHTUNG: flowCharts, tasks und connections sind RUNTIME-RELEVANT!
        // Sie enthalten die Task-Sequenzen für Spiel-Logik (Bounce, Score, Navigation).
        // Nur echte Editor-Metadaten entfernen:
        const editorOnlyKeys = ['flow', 'flowGraph', 'nodePositions', 'description', 'details', 'showDetails'];

        Object.keys(obj).forEach(key => {
            // Remove keys in editor-only list or known noisy internal React/Vue keys
            if (editorOnlyKeys.includes(key) || key === '__v_isRef' || key === '__v_raw') {
                delete obj[key];
            } else {
                this.deepClean(obj[key]);
            }
        });
    }

    /**
     * Generate a complete standalone HTML file with embedded runtime
     */
    public generateStandaloneHTML(project: any, runtimeJS: string): string {
        // S-01: </script>-Sequenzen escapen um HTML-Injection zu verhindern
        // (gilt auch bei type="application/json", da der HTML-Parser trotzdem </script> erkennt)
        const projectJSON = JSON.stringify(project, null, 2)
            .replace(/<\/script>/gi, '</script>')
            .replace(/<!--/g, '<!--');
        const mainStage = project.stages?.find((s: any) => s.type === 'main') || project.stages?.[0] || project.stage;
        const gridConfig = mainStage?.grid || { cols: 20, rows: 15, cellSize: 32, backgroundColor: '#ffffff' };
        const stageWidth = gridConfig.cols * gridConfig.cellSize;
        const stageHeight = gridConfig.rows * gridConfig.cellSize;
        const pwaHead = this.generatePWAHead(project);

        return `<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
${pwaHead}
    <title>${SecurityUtils.escapeHtml(project.meta.name || 'New Game')}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden;
            background: #0f172a;
        }
        body {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        }
        #stage-container {
            position: relative;
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }
        #run-stage {
            position: relative;
            width: ${stageWidth}px;
            height: ${stageHeight}px;
            background: ${gridConfig.backgroundColor || '#ffffff'};
            box-shadow: 0 20px 50px rgba(0,0,0,0.5);
            border-radius: 4px;
            overflow: hidden;
            transform-origin: center center;
            flex-shrink: 0;
            touch-action: none; /* Verhindert Browser-Scroll/Zoom auf Touch-Geräten */
        }
        .game-object {
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            box-sizing: border-box;
            overflow: hidden;
            user-select: none;
        }
    </style>
</head>
<body>
    <div id="stage-container">
        <div id="run-stage"></div>
    </div>
    
    <script>
    // ═══════════════════════════════════════════════════════════════
    // Standalone Runtime Bundle (Shared Logic)
    // ═══════════════════════════════════════════════════════════════
    ${runtimeJS}

    // ═══════════════════════════════════════════════════════════════
    // Start Game
    // ═══════════════════════════════════════════════════════════════
    </script>
    <script type="application/json" id="gcs-project-data">
${projectJSON}
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        if (typeof window.startStandalone === 'function') {
            try {
                const projectDataStr = document.getElementById('gcs-project-data').textContent;
                window.PROJECT = JSON.parse(projectDataStr);
                window.startStandalone(window.PROJECT);
            } catch (e) {
                logger.error('Failed to parse project data:', e);
                document.body.innerHTML = '<h2 style="color:white;text-align:center;margin-top:20%">Error: Project initialization failed.</h2>';
            }
        } else {
            logger.error('Standalone Runtime not found! Check if runtime-standalone.js was bundled correctly.');
            document.body.innerHTML = '<h2 style="color:white;text-align:center;margin-top:20%">Error: Runtime not found.</h2>';
        }
    });
    </script>
</body>
</html>`;
    }

    /**
     * Generate a compressed standalone HTML file with gzip-encoded project data
     */
    private generateCompressedHTML(project: any, runtimeJS: string): string {
        const compressedData = this.compressProject(project);
        const mainStage = project.stages?.find((s: any) => s.type === 'main') || project.stages?.[0] || project.stage;
        const gridConfig = mainStage?.grid || { cols: 20, rows: 15, cellSize: 32, backgroundColor: '#ffffff' };
        const stageWidth = gridConfig.cols * gridConfig.cellSize;
        const stageHeight = gridConfig.rows * gridConfig.cellSize;

        const pwaHead = this.generatePWAHead(project);

        return `<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
${pwaHead}
    <title>${SecurityUtils.escapeHtml(project.meta.name || 'New Game')}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden;
            background: #0f172a;
        }
        body {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        }
        #stage-container {
            position: relative;
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }
        #run-stage {
            position: relative;
            width: ${stageWidth}px;
            height: ${stageHeight}px;
            background: ${gridConfig.backgroundColor || '#ffffff'};
            box-shadow: 0 20px 50px rgba(0,0,0,0.5);
            border-radius: 4px;
            overflow: hidden;
            transform-origin: center center;
            flex-shrink: 0;
            touch-action: none; /* Verhindert Browser-Scroll/Zoom auf Touch-Geräten */
        }
        .game-object {
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            box-sizing: border-box;
            overflow: hidden;
            user-select: none;
        }
    </style>
</head>
<body>
    <div id="stage-container">
        <div id="run-stage"></div>
    </div>
    
    <script>
    // ═══════════════════════════════════════════════════════════════
    // Standalone Runtime Bundle (Shared Logic)
    // ═══════════════════════════════════════════════════════════════
    ${runtimeJS}

    // ═══════════════════════════════════════════════════════════════
    // Compressed Project Data (gzip + Base64)
    // ═══════════════════════════════════════════════════════════════
    window.PROJECT_DATA = "${compressedData}";
    
    document.addEventListener('DOMContentLoaded', () => {
        if (typeof window.startStandalone === 'function') {
            // Runtime will detect PROJECT_DATA and decompress automatically
            window.startStandalone(null);
        } else {
            logger.error('Standalone Runtime not found!');
            document.body.innerHTML = '<h2 style="color:white;text-align:center;margin-top:20%">Error: Runtime not found.</h2>';
        }
    });
    </script>
</body>
</html>`;
    }

    /**
     * Finds and embeds all media references (Images, Audio) in the project as Base64 Data URLs.
     */
    private async embedMedia(project: any): Promise<void> {
        const mediaRefs = new Map<string, string>(); // path -> dataUrl

        const mediaExtensions = /\.(png|jpg|jpeg|gif|svg|webp|bmp|ico|mp3|ogg|wav|mp4|webm)$/i;
        const isMediaPath = (s: string) => {
            if (!s || typeof s !== 'string' || s.length === 0) return false;
            if (s.startsWith('data:') || s.startsWith('http://') || s.startsWith('https://')) return false;
            return (/(^|\/)(images|audio|video|assets)\//i).test(s) || mediaExtensions.test(s);
        };

        // Build a map of known variables and lists for resolving ${...} bindings
        const varMap = new Map<string, any>();
        const collectVariables = (obj: any) => {
            if (Array.isArray(obj)) {
                obj.forEach(collectVariables);
                return;
            }
            if (!obj || typeof obj !== 'object') return;
            if ((obj.className === 'TVariable' || obj.className === 'Variable') && typeof obj.name === 'string') {
                varMap.set(obj.name, obj.value);
            }
            if ((obj.className === 'TListVariable' || obj.className === 'ListVariable') && typeof obj.name === 'string' && Array.isArray(obj.items)) {
                varMap.set(obj.name, obj.items);
            }
            Object.values(obj).forEach(collectVariables);
        };
        collectVariables(project);

        const resolveBinding = (s: string, depth = 3): string | undefined => {
            if (typeof s !== 'string') return undefined;
            const m = s.match(/^\s*\$\{([^}]+)\}\s*$/);
            if (!m || depth <= 0) return undefined;
            const expr = m[1].trim();

            // Array index access: List_15[0]
            const idxMatch = expr.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*\[\s*(\d+)\s*\]$/);
            if (idxMatch) {
                const list = varMap.get(idxMatch[1]);
                if (Array.isArray(list)) {
                    const resolved = list[parseInt(idxMatch[2], 10)];
                    if (typeof resolved === 'string' && resolved) {
                        return resolveBinding(resolved, depth - 1) ?? resolved;
                    }
                    return typeof resolved === 'string' ? resolved : undefined;
                }
                return undefined;
            }

            const val = varMap.get(expr);
            if (typeof val === 'string' && val) return resolveBinding(val, depth - 1) ?? val;
            if (typeof val === 'string') return val;
            if (val !== undefined && val !== null) return String(val);
            return undefined;
        };

        // 1. Collect all unique media paths from the project recursively
        const collectPaths = (obj: any) => {
            const tryCollect = (s: string) => {
                if (isMediaPath(s)) {
                    mediaRefs.set(s, '');
                } else {
                    const resolved = resolveBinding(s);
                    if (typeof resolved === 'string' && isMediaPath(resolved)) {
                        mediaRefs.set(resolved, '');
                    }
                }
            };
            if (Array.isArray(obj)) {
                obj.forEach((item: any) => {
                    if (typeof item === 'string') {
                        tryCollect(item);
                    } else if (item && typeof item === 'object') {
                        collectPaths(item);
                    }
                });
                return;
            }
            if (!obj || typeof obj !== 'object') return;

            Object.values(obj).forEach((val: any) => {
                if (typeof val === 'string') {
                    tryCollect(val);
                } else if (val && typeof val === 'object') {
                    collectPaths(val);
                }
            });
        };

        collectPaths(project);

        // 2. Fetch and convert to Base64
        logger.info(`[GameExporter] Found ${mediaRefs.size} unique media files to embed.`);
        for (const [path, _] of mediaRefs) {
            try {
                // Strip leading / or ./ so the path is always relative to the app root
                let relativePath = path;
                if (relativePath.startsWith('./')) {
                    relativePath = relativePath.substring(2);
                }
                if (relativePath.startsWith('/')) {
                    relativePath = relativePath.substring(1);
                }
                const baseUrl = project.meta?.baseUrl || network.getHttpUrl() || window.location.href;
                const url = new URL(relativePath, baseUrl).href;

                const urls = [url];
                if (!relativePath.startsWith('images/')) {
                    urls.push(new URL(`images/${relativePath}`, baseUrl).href);
                }

                let embedded = false;
                for (const tryUrl of urls) {
                    logger.info(`[GameExporter] Fetching media: ${tryUrl}`);
                    const resp = await fetch(tryUrl);
                    if (resp.ok) {
                        const contentType = resp.headers.get('content-type') || '';
                        if (contentType.includes('text/html')) {
                            logger.warn(`[GameExporter] Media path returned HTML, not a media file: ${tryUrl}`);
                        } else {
                            const blob = await resp.blob();
                            const dataUrl = await this.blobToDataUrl(blob);
                            mediaRefs.set(path, dataUrl);
                            logger.info(`[GameExporter] Successfully embedded: ${path} from ${tryUrl}`);
                            embedded = true;
                            break;
                        }
                    }
                }
                if (!embedded) {
                    logger.warn(`[GameExporter] Failed to embed media: ${path}`);
                }
            } catch (e) {
                logger.warn(`[GameExporter] Network error embedding media: ${path}`, e);
            }
        }

        // 3. Replace paths with Data URLs in the project recursively
        const replacePaths = (obj: any) => {
            if (Array.isArray(obj)) {
                obj.forEach((item: any, i: number) => {
                    if (typeof item === 'string' && mediaRefs.has(item)) {
                        const dataUrl = mediaRefs.get(item);
                        if (dataUrl) obj[i] = dataUrl;
                    } else if (item && typeof item === 'object') {
                        replacePaths(item);
                    }
                });
                return;
            }
            if (!obj || typeof obj !== 'object') return;

            Object.keys(obj).forEach(key => {
                const val = obj[key];
                if (typeof val === 'string' && mediaRefs.has(val)) {
                    const dataUrl = mediaRefs.get(val);
                    if (dataUrl) obj[key] = dataUrl;
                } else if (val && typeof val === 'object') {
                    replacePaths(val);
                }
            });
        };

        replacePaths(project);
    }

    /**
     * Convert a Blob to a Base64 Data URL
     */
    private blobToDataUrl(blob: Blob): Promise<string> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    }

    // D-02: escapeHtml wurde auf SecurityUtils.escapeHtml() konsolidiert (kein Duplikat mehr)

    /**
     * Trigger file download.
     * Unterstützt: Electron (window.electronFS) > FileSystem Access API > Blob-Download.
     */
    private async downloadFile(content: string, filename: string, mimeType: string): Promise<void> {
        // 1. Electron-Modus (IPC-Bridge) inkl native Dialog
        if ((window as any).electronFS) {
            try {
                const ext = mimeType === 'text/html' ? 'html' : 'json';
                const fileType = mimeType === 'text/html' ? 'HTML Game' : 'JSON Game Project';
                const targetPath = await (window as any).electronFS.showSaveDialog({
                    defaultPath: filename,
                    filters: [{ name: fileType, extensions: [ext] }]
                });
                
                if (!targetPath) return; // User canceled
                
                await (window as any).electronFS.writeFile(targetPath, content);
                NotificationToast.show(`Export erfolgreich!\n\nDatei: ${targetPath}`);
                return;
            } catch (err) {
                logger.warn('Electron FS failed, falling back:', err);
            }
        }

        // 2. FileSystem Access API (modern browsers)
        if ('showSaveFilePicker' in window) {
            try {
                const handle = await (window as any).showSaveFilePicker({
                    suggestedName: filename,
                    types: [{
                        description: mimeType === 'text/html' ? 'HTML Game File' : 'JSON Game File',
                        accept: { [mimeType]: [mimeType === 'text/html' ? '.html' : '.json'] }
                    }]
                });
                const writable = await handle.createWritable();
                await writable.write(content);
                await writable.close();
                NotificationToast.show(`Game exported successfully!\n\nFile: ${handle.name}\n\nOpen it in any browser to play.`);
                return;
            } catch (err: any) {
                if (err.name === 'AbortError') return;
                logger.warn('File System Access API failed, using fallback:', err);
            }
        }

        // 3. Fallback: Blob-Download
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        setTimeout(() => document.body.removeChild(a), 2000);
        NotificationToast.show(`Game exported to Downloads folder.\n\nFile: ${filename}`);
    }

    /**
     * Generiert PWA-Head-Markup: ein data-URI Manifest und Apple-Meta-Tags.
     * Im Single-File-Export kann keine separate manifest.json ausgeliefert werden,
     * deshalb wird das Manifest inline als data:application/json;base64 verpackt.
     */
    private generatePWAHead(project: any): string {
        const name = SecurityUtils.escapeHtml(project.meta?.name || 'GCS Spiel');
        const shortName = name.length > 12 ? name.substring(0, 9) + '...' : name;
        const themeColor = '#0f172a';
        const backgroundColor = '#0f172a';

        const manifest = {
            name: project.meta?.name || 'GCS Spiel',
            short_name: shortName,
            start_url: '.',
            display: 'standalone',
            background_color: backgroundColor,
            theme_color: themeColor,
            lang: 'de',
            orientation: 'any',
            icons: [
                { src: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxOTIiIGhlaWdodD0iMTkyIiB2aWV3Qm94PSIwIDAgMTkyIDE5MiI+PHJlY3Qgd2lkdGg9IjE5MiIgaGVpZ2h0PSIxOTIiIGZpbGw9IiMwZjE3MmEiLz48dGV4dCB4PSI5NiIgeT0iMTEwIiBmb250LXNpemU9IjcwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjNGZhY2ZlIj7wn5iBPC90ZXh0Pjwvc3ZnPg==', sizes: '192x192', type: 'image/svg+xml' }
            ]
        };

        const manifestJson = JSON.stringify(manifest);
        const manifestB64 = btoa(manifestJson);

        return `    <meta name="theme-color" content="${themeColor}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="${name}">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="data:application/json;base64,${manifestB64}">`;
    }
}
