import fs from 'node:fs';
import {AgentController} from '../src/services/AgentController';
import {projectStore} from '../src/services/ProjectStore';
import {coreStore} from '../src/services/registry/CoreStore';
import {TServerProfile} from '../src/components/TServerProfile';
const file='game-server/public/projects/GCS-CMS.json',project=JSON.parse(fs.readFileSync(file,'utf8'));
if(project.stages.some((s:any)=>s.objects?.some((o:any)=>o.name==='MeinBereich')))throw Error('Profilbereich bereits vorhanden');
fs.copyFileSync(file,file+'.before-profile');
projectStore.setProject(project);coreStore.setProject(project);const agent=AgentController.getInstance();agent.setProject(project);const main='stage_main',bp='stage_blueprint';coreStore.setActiveStageId(main);
const button=(name:string,x:number,y:number,width:number,text:string)=>agent.addObject(main,{className:'TButton',id:'profile_'+name,name,x,y,width,height:3,text,visible:false,style:{backgroundColor:'#285464',color:'#fff',fontSize:22,borderRadius:10}});
button('MeinBereich',39,2,8,'👤');button('ProfilSpeichern',7,23,20,'✓ Speichern');button('ProfilHilfe',30,23,26,'🆘 Zugangshilfe');button('ProfilZurueck',7,29,18,'⬅ Räume');
agent.addObject(main,{className:'TEdit',id:'profile_name',name:'ProfilName',x:7,y:11,width:48,height:3,text:'',placeholder:'Dein Anzeigename',maxLength:40,visible:false});
agent.createLabel(main,'ProfilAvatar',7,15,'🦊',{width:48,height:3,visible:false,fontSize:30,color:'#fff'});agent.setProperty(main,'ProfilAvatar','id','profile_avatar');
const avatars=['🦊','🦉','🐶','🐱','🐼','🐸','🦁','🐰'];avatars.forEach((v,i)=>button('ProfilAvatar'+i,7+i*6,19,5,v));
const widgets=['ProfilName','ProfilAvatar','ProfilSpeichern','ProfilHilfe','ProfilZurueck',...avatars.map((_,i)=>'ProfilAvatar'+i)];
const vis=(list:string[],value:boolean)=>Object.fromEntries(list.map(n=>[n+'.visible',value]));
const task=(n:string)=>agent.createTask(bp,n,n),action=(n:string,type:any,name:string,params:any)=>agent.addAction(n,type,name,params),prop=(n:string,name:string,changes:any)=>action(n,'property',name,{changes});
['Profil_Oeffnen','Profil_Laden','Profil_Anzeigen','Profil_Speichern','Profil_Hilfe_Anfordern','Profil_Rueckmeldung','Profil_Fehler','Profil_Verbergen','Profil_Zurueck'].forEach(task);
agent.addBranch('Profil_Oeffnen','Busy','==',0,b=>b.addTaskCall('Profil_Laden'));
const request=(n:string,op:string,body:any)=>{prop(n,'Act_'+n+'_Warten',{Busy:1,'Hinweis.text':'⏳ Einen Moment …'});action(n,'http','Act_'+n+'_Serveranfrage',{url:'/api/cms/profile/'+op,method:'POST',body:{token:'${Token}',...body},resultVariable:'ProfilAntwort'});};
request('Profil_Laden','read',{});agent.addBranch('Profil_Laden','ProfilAntwort.ok','==',true,b=>b.addTaskCall('Profil_Anzeigen'),b=>b.addTaskCall('Profil_Fehler'));
prop('Profil_Anzeigen','Act_Profilfelder_Anzeigen',{Busy:0,Modus:'profile',...vis(widgets,true),...vis(['Karte0','Karte1','Karte2','Karte3','Zurueck','Vorher','Weiter'],false),'ProfilName.text':'${ProfilAntwort.name}','ProfilAvatar.text':'${ProfilAntwort.avatar}','Hinweis.text':'${ProfilAntwort.message}'});
request('Profil_Speichern','save',{name:'${ProfilName.text}',avatar:'${ProfilAvatar.text}'});agent.addTaskCall('Profil_Speichern','Profil_Rueckmeldung');
request('Profil_Hilfe_Anfordern','help',{});agent.addTaskCall('Profil_Hilfe_Anfordern','Profil_Rueckmeldung');
prop('Profil_Rueckmeldung','Act_Profilantwort_Anzeigen',{Busy:0,'Hinweis.text':'${ProfilAntwort.message}'});
agent.addBranch('Profil_Rueckmeldung','ProfilAntwort.ok','==',true,b=>b.addTaskCall('Profil_Titel_Aktualisieren'),b=>b.addTaskCall('Profil_Fehler'));
task('Profil_Titel_Aktualisieren');prop('Profil_Titel_Aktualisieren','Act_Aktuellen_Namen_Anzeigen',{'Titel.text':'${ProfilAntwort.avatar}  ${ProfilAntwort.name}'});
prop('Profil_Fehler','Act_Profilfehler_Anzeigen',{Busy:0,'Hinweis.text':'⚠ Nicht gespeichert. Eingaben und Verbindung prüfen.'});
prop('Profil_Verbergen','Act_Profilfelder_Verbergen',{...vis(widgets,false),'ProfilName.text':''});agent.addTaskCall('Profil_Zurueck','Profil_Verbergen');agent.addTaskCall('Profil_Zurueck','Raeume');
for(const [obj,t]of [['MeinBereich','Profil_Oeffnen'],['ProfilSpeichern','Profil_Speichern'],['ProfilHilfe','Profil_Hilfe_Anfordern'],['ProfilZurueck','Profil_Zurueck']]){const gate='Profil_Sperre_'+obj;task(gate);agent.addBranch(gate,'Busy','==',0,b=>b.addTaskCall(t));agent.connectEvent(main,obj,'onClick',gate);}
avatars.forEach((v,i)=>{const n='Profil_Avatar_'+i;task(n);prop(n,'Act_Avatar_'+i+'_Waehlen',{'ProfilAvatar.text':v});agent.connectEvent(main,'ProfilAvatar'+i,'onClick',n)});
prop('Angemeldet','Act_Profilzugang_Anzeigen',{'MeinBereich.visible':true});
agent.addTaskCall('LoginZeigen','Profil_Verbergen');prop('LoginZeigen','Act_Profilzugang_Verbergen',{'MeinBereich.visible':false});
const names=project.stages[0].tasks.filter((t:any)=>t.name.startsWith('Profil_')).map((t:any)=>t.name);
agent.createFeature(main,{id:'personal-profile',name:'Meinen persönlichen Bereich verwalten',description:'Eigenen Namen und Avatar bearbeiten oder Zugangshilfe anfordern',blueprintTaskNames:names,userStoryIds:['personal-profile-story']});
const stories=project.userStories||{userStories:[]};projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'userStories',value:{...stories,userStories:[...(stories.userStories||[]),{id:'personal-profile-story',title:'Meinen persönlichen Bereich öffnen',projectId:project.meta.id,featureId:'personal-profile',status:'completed',priority:'high',description:'Profil lesen → bearbeiten → speichern; bei Zugangsproblemen Hilfe anfordern',plannedComponent:{name:'MeinBereich',type:'TButton'},plannedEvent:'onClick',plannedTask:'Profil_Oeffnen',relatedStages:[main],relatedComponents:['MeinBereich']}]}});
projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'activeStageId',value:main});
fs.writeFileSync(file,JSON.stringify(project,null,2));
const htmlFile='public/cms.html';fs.copyFileSync(htmlFile,htmlFile+'.before-profile');let html=fs.readFileSync(htmlFile,'utf8');const start=html.indexOf('window.PROJECT=')+'window.PROJECT='.length,end=html.indexOf('</script>',start);if(start<15||end<start)throw Error('CMS-Host nicht erkannt');html=html.slice(0,start)+JSON.stringify(project).replace(/</g,'\\u003c')+html.slice(end);fs.writeFileSync(htmlFile,html);
const node=new TServerProfile();node.id='server_profile';node.events={onRead:'Eigenes_Profil_Lesen',onSave:'Eigenes_Profil_Speichern',onHelp:'Zugangshilfe_Anfordern'};
const actions=['read','save','help'].map((method,i)=>({id:'profile_action_'+i,name:['Act_Eigenes_Profil_Lesen','Act_Eigenes_Profil_Speichern','Act_Zugangshilfe_Anfordern'][i],type:'call_method',target:node.name,method,params:[]}));
const tasks=Object.values(node.events).map((name,i)=>({id:'profile_task_'+i,name,description:name,actionSequence:[{type:'action',name:actions[i].name}]}));
const server={meta:{id:'gcs-server-profile',name:'GCS-Server-Profil',version:'1.0.0'},activeStageId:bp,stage:project.stage,objects:[],actions:[],tasks:[],variables:[],stages:[{id:bp,type:'blueprint',name:'Persönlicher Bereich',grid:project.stages[0].grid,objects:[node.toDTO()],tasks,actions,variables:[],features:[{id:'server-profile',name:'Eigene Profilangaben verwalten',blueprintTaskNames:tasks.map(t=>t.name)}]}]};projectStore.setProject(server);fs.writeFileSync('game-server/public/projects/GCS-Server-Profil.json',JSON.stringify(server,null,2));
console.log('Profilbereich additiv ergänzt; vorherige Projektdatei gesichert.');
