import fs from 'node:fs';import {AgentController} from '../src/services/AgentController';import {projectStore} from '../src/services/ProjectStore';import {coreStore} from '../src/services/registry/CoreStore';import {TServerUpload} from '../src/components/TServerUpload';
const folder='game-server/public/projects/',file=folder+'GCS-CMS-Spiele.json';if(fs.existsSync(file))throw Error('Upload-Projekte sind bereits vorhanden.');
const grid={cols:64,rows:48,cellSize:18,visible:false,backgroundColor:'#122b39'},bp='stage_blueprint',main='stage_main';
const project:any={meta:{id:'gcs-cms-library',name:'GCS-CMS-Spiele',version:'1.0.0'},stage:{grid},stages:[],objects:[],actions:[],tasks:[],variables:[],activeStageId:main};
const agent=AgentController.getInstance();function use(p:any){projectStore.setProject(p);coreStore.setProject(p);agent.setProject(p);coreStore.setActiveStageId(main)}use(project);agent.createStage(bp,'Upload-Dienste','blueprint',{grid});agent.createStage(main,'Eigene Spiele','main',{grid});
const button=(n:string,x:number,y:number,w:number,text:string,visible=true)=>agent.addObject(main,{id:'upload_'+n,className:'TButton',name:n,x,y,width:w,height:3,text,visible,style:{backgroundColor:'#285464',color:'#fff',fontSize:18,borderRadius:8}});
const label=(n:string,x:number,y:number,text:string)=>{agent.createLabel(main,n,x,y,text,{width:56,height:2,fontSize:18,color:'#fff'});agent.setProperty(main,n,'id','upload_'+n)};
const t=(n:string)=>agent.createTask(bp,n,n),a=(n:string,type:any,name:string,params:any)=>agent.addAction(n,type,name,params),p=(n:string,name:string,changes:any)=>a(n,'property',name,{changes});
function uploadComponents(prefix:string,kind:string){agent.addObject(bp,{id:prefix+'picker',className:'TFilePicker',name:prefix+'Datei',x:1,y:1,accept:kind==='game'?'.json':'.png,.jpg,.jpeg,.webp',maxBytes:kind==='game'?10485760:2097152});agent.addObject(bp,{id:prefix+'upload',className:'TFileUpload',name:prefix+'Upload',x:1,y:4,picker:prefix+'Datei',endpoint:'/api/cms/upload/'+kind});}
uploadComponents('Spiel','game');
label('Titel',4,2,'MEINE SPIELE');label('Status',4,5,'GCS-Projekt auswählen · maximal 10 MB');
agent.addObject(main,{id:'game_title',className:'TEdit',name:'SpielTitel',x:4,y:9,width:54,height:3,text:'',placeholder:'Titel des Spiels',maxLength:60});agent.addObject(main,{id:'game_description',className:'TEdit',name:'SpielBeschreibung',x:4,y:13,width:54,height:3,text:'',placeholder:'Kurze Beschreibung',maxLength:500});
button('DateiWaehlen',4,18,18,'📁 Datei auswählen');button('Hochladen',24,18,18,'📤 Hochladen');button('Abbrechen',44,18,14,'Abbrechen');
label('Auswahl',4,23,'Spiel anklicken, um es auszuwählen.');for(let i=0;i<4;i++)button('SpielKarte'+i,4+(i%2)*28,27+Math.floor(i/2)*4,26,'',false);
button('Veroeffentlichen',4,37,25,'Veröffentlichen');button('Zurueckziehen',32,37,26,'Als Entwurf zurückziehen');button('Vorher',4,42,8,'◀');button('Weiter',14,42,8,'▶');
agent.addObject(main,{id:'library_back',className:'TLink',name:'SuperAdminOeffnen',x:32,y:43,width:25,height:2,text:'Zur SuperAdmin-Verwaltung',url:'/super',target:'_self'});
for(const [n,v]of Object.entries({SpielId:'',Seite:0,Seiten:0,Slot0:'',Slot1:'',Slot2:'',Slot3:''}))agent.addVariable(n,typeof v==='number'?'integer':'string',v,'global');
['Spiel_Datei_Waehlen','Spiel_Upload_Starten','Spiel_Upload_Abbrechen','Spiel_Datei_Bereit','Spiel_Upload_Status','Spiel_Upload_Erfolgreich','Spiele_Laden','Spiele_Anzeigen','Spiele_Veroeffentlichen','Spiele_Zurueckziehen','Spiele_Vorher','Spiele_Weiter'].forEach(t);
a('Spiel_Datei_Waehlen','call_method','Act_Spiel_Dateiauswahl_Oeffnen',{target:'SpielDatei',method:'choose',params:[]});a('Spiel_Upload_Starten','call_method','Act_Spiel_Datei_Uebertragen',{target:'SpielUpload',method:'start',params:['${SpielTitel.text}','${SpielBeschreibung.text}']});a('Spiel_Upload_Abbrechen','call_method','Act_Spiel_Upload_Abbrechen',{target:'SpielUpload',method:'cancel',params:[]});
p('Spiel_Datei_Bereit','Act_Dateiname_Anzeigen',{'Status.text':'${SpielDatei.filename} · bereit zum Hochladen'});p('Spiel_Upload_Status','Act_Upload_Status_Anzeigen',{'Status.text':'${SpielUpload.message} (${SpielUpload.progress} %)'});p('Spiel_Upload_Erfolgreich','Act_Neuen_Entwurf_Auswaehlen',{SpielId:'${SpielUpload.result.id}','Auswahl.text':'Neuer Entwurf · veröffentlichen und anschließend einem Raum freigeben.'});agent.addTaskCall('Spiel_Upload_Erfolgreich','Spiele_Laden');
const http=(n:string,body:any)=>a(n,'http','Act_'+n+'_Anfragen',{url:'/api/cms/upload-library',method:'POST',body,resultVariable:'Antwort'});
http('Spiele_Laden',{page:'${Seite}'});agent.addTaskCall('Spiele_Laden','Spiele_Anzeigen');p('Spiele_Anzeigen','Act_Eigene_Spiele_Anzeigen',{'Status.text':'${Antwort.message}',Seite:'${Antwort.page}',Seiten:'${Antwort.pages}',...Object.fromEntries([0,1,2,3].flatMap(i=>[['SpielKarte'+i+'.visible','${Antwort.slot'+i+'.visible}'],['SpielKarte'+i+'.text','${Antwort.slot'+i+'.label}'],['Slot'+i,'${Antwort.slot'+i+'.id}']]))});
for(const [n,published]of [['Spiele_Veroeffentlichen',true],['Spiele_Zurueckziehen',false]]as const){http(n,{operation:'publish',id:'${SpielId}',published,page:'${Seite}'});agent.addTaskCall(n,'Spiele_Anzeigen')}
for(let i=0;i<4;i++){const n='Spiel_'+i+'_Auswaehlen';t(n);p(n,'Act_Spiel_'+i+'_Auswaehlen',{SpielId:'${Slot'+i+'}','Auswahl.text':'${SpielKarte'+i+'.text}'});agent.connectEvent(main,'SpielKarte'+i,'onClick',n)}
a('Spiele_Vorher','calculate','Act_Vorherige_Spielseite',{formula:'Math.max(0, Seite - 1)',resultVariable:'Seite'});agent.addTaskCall('Spiele_Vorher','Spiele_Laden');a('Spiele_Weiter','calculate','Act_Naechste_Spielseite',{formula:'Math.min(Math.max(0, Seiten - 1), Seite + 1)',resultVariable:'Seite'});agent.addTaskCall('Spiele_Weiter','Spiele_Laden');
for(const [obj,task]of [['DateiWaehlen','Spiel_Datei_Waehlen'],['Hochladen','Spiel_Upload_Starten'],['Abbrechen','Spiel_Upload_Abbrechen'],['Veroeffentlichen','Spiele_Veroeffentlichen'],['Zurueckziehen','Spiele_Zurueckziehen'],['Vorher','Spiele_Vorher'],['Weiter','Spiele_Weiter']])agent.connectEvent(main,obj,'onClick',task);
agent.connectEvent(bp,'SpielDatei','onSelected','Spiel_Datei_Bereit');t('Spiel_Dateifehler');p('Spiel_Dateifehler','Act_Dateifehler_Anzeigen',{'Status.text':'${SpielDatei.message}'});agent.connectEvent(bp,'SpielDatei','onError','Spiel_Dateifehler');
for(const event of ['onStarted','onProgress','onError','onCancel'])agent.connectEvent(bp,'SpielUpload',event,'Spiel_Upload_Status');agent.connectEvent(bp,'SpielUpload','onSuccess','Spiel_Upload_Erfolgreich');
agent.createTimer(main,'UploadInitialLaden',1,1,{interval:350,enabled:true,maxInterval:1});agent.setProperty(main,'UploadInitialLaden','id','library_timer');agent.connectEvent(main,'UploadInitialLaden','onTimer','Spiele_Laden');
agent.createFeature(main,{id:'game-upload',name:'Eigene Spiele hochladen und veröffentlichen',description:'Datei auswählen → übertragen → als Entwurf prüfen → veröffentlichen → im Raum freigeben',blueprintTaskNames:project.stages[0].tasks.map((x:any)=>x.name)});
projectStore.dispatch({type:'SET_PROPERTY',target:project.stages[0],path:'variables',value:project.variables});projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'variables',value:[]});projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'activeStageId',value:main});fs.writeFileSync(file,JSON.stringify(project,null,2));
// Extend the existing personal area without rebuilding its existing tasks.
const profileFile=folder+'GCS-CMS.json',profile=JSON.parse(fs.readFileSync(profileFile,'utf8'));fs.copyFileSync(profileFile,profileFile+'.before-upload');use(profile);uploadComponents('Avatar','avatar');
button('AvatarDateiWaehlen',7,34,16,'📁 Eigenes Bild',false);button('AvatarHochladen',25,34,16,'📤 Übertragen',false);button('AvatarAbbrechen',43,34,13,'Abbrechen',false);agent.addObject(main,{id:'own_avatar_image',className:'TImage',name:'ProfilBild',x:56,y:12,width:6,height:6,src:'',visible:false});
['Avatar_Waehlen','Avatar_Uebertragen','Avatar_Abbrechen','Avatar_Status','Avatar_Bereit','Avatar_Gespeichert'].forEach(t);
a('Avatar_Waehlen','call_method','Act_Avatar_Dateiauswahl_Oeffnen',{target:'AvatarDatei',method:'choose',params:[]});a('Avatar_Uebertragen','call_method','Act_Avatar_Uebertragen',{target:'AvatarUpload',method:'start',params:['','','${Token}']});a('Avatar_Abbrechen','call_method','Act_Avatar_Upload_Abbrechen',{target:'AvatarUpload',method:'cancel',params:[]});
p('Avatar_Status','Act_Avatar_Uploadstatus_Anzeigen',{'Hinweis.text':'${AvatarUpload.message} (${AvatarUpload.progress} %)'});p('Avatar_Bereit','Act_Avatar_Dateiname_Anzeigen',{'Hinweis.text':'${AvatarDatei.filename} · bereit'});p('Avatar_Gespeichert','Act_Avatarbild_Anzeigen',{'ProfilBild.src':'${AvatarUpload.result.avatarImage}','Hinweis.text':'${AvatarUpload.message}'});
for(const [obj,task]of [['AvatarDateiWaehlen','Avatar_Waehlen'],['AvatarHochladen','Avatar_Uebertragen'],['AvatarAbbrechen','Avatar_Abbrechen']])agent.connectEvent(main,obj,'onClick',task);
agent.connectEvent(bp,'AvatarDatei','onSelected','Avatar_Bereit');t('Avatar_Dateifehler');p('Avatar_Dateifehler','Act_Avatar_Dateifehler_Anzeigen',{'Hinweis.text':'${AvatarDatei.message}'});agent.connectEvent(bp,'AvatarDatei','onError','Avatar_Dateifehler');for(const event of ['onStarted','onProgress','onError','onCancel'])agent.connectEvent(bp,'AvatarUpload',event,'Avatar_Status');agent.connectEvent(bp,'AvatarUpload','onSuccess','Avatar_Gespeichert');
const names=['AvatarDateiWaehlen','AvatarHochladen','AvatarAbbrechen','ProfilBild'];p('Profil_Anzeigen','Act_Avatarupload_Anzeigen',{...Object.fromEntries(names.map(n=>[n+'.visible',true])),'ProfilBild.src':'${ProfilAntwort.avatarImage}'});p('Profil_Verbergen','Act_Avatarupload_Verbergen',Object.fromEntries(names.map(n=>[n+'.visible',false])));agent.addTaskCall('Profil_Verbergen','Avatar_Abbrechen');
agent.createFeature(main,{id:'avatar-upload',name:'Eigenes Avatarbild hochladen',blueprintTaskNames:['Avatar_Waehlen','Avatar_Uebertragen','Avatar_Abbrechen','Avatar_Status','Avatar_Bereit','Avatar_Gespeichert']});projectStore.dispatch({type:'SET_PROPERTY',target:profile,path:'activeStageId',value:main});fs.writeFileSync(profileFile,JSON.stringify(profile,null,2));
const htmlFile='public/cms.html';let html=fs.readFileSync(htmlFile,'utf8'),start=html.indexOf('window.PROJECT=')+15,end=html.indexOf('</script>',start);fs.writeFileSync(htmlFile,html.slice(0,start)+JSON.stringify(profile).replace(/</g,'\\u003c')+html.slice(end));
const superFile=folder+'GCS-CMS-SuperAdmin.json',superProject=JSON.parse(fs.readFileSync(superFile,'utf8'));use(superProject);agent.addObject(main,{id:'library_link',className:'TLink',name:'SpieleVerwalten',x:40,y:3,width:20,height:2,text:'🎮 Meine Spiele',url:'/library',target:'_self'});projectStore.dispatch({type:'SET_PROPERTY',target:superProject,path:'activeStageId',value:main});fs.writeFileSync(superFile,JSON.stringify(superProject,null,2));let sh=fs.readFileSync('public/cms-super.html','utf8'),sa=sh.indexOf('window.PROJECT=')+15,sb=sh.indexOf('</script>',sa);fs.writeFileSync('public/cms-super.html',sh.slice(0,sa)+JSON.stringify(superProject).replace(/</g,'\\u003c')+sh.slice(sb));
const nodes=['game','avatar'].map((kind,i)=>{const n=new TServerUpload(kind==='game'?'SpielUploadVerarbeiten':'AvatarUploadVerarbeiten',2,2+i*6);n.id='server_upload_'+kind;n.kind=kind;n.maxBytes=kind==='game'?10485760:2097152;n.successMessage=kind==='game'?'✓ Spiel als Entwurf gespeichert.':'✓ Eigenes Avatarbild gespeichert.';n.events={onRequest:kind==='game'?'Spiel_Upload_Verarbeiten':'Avatar_Upload_Verarbeiten'};return n});
const actions=nodes.map((n,i)=>({id:'upload_action_'+i,name:'Act_'+n.name,type:'call_method',target:n.name,method:'execute',params:[]})),tasks=nodes.map((n,i)=>({id:'upload_task_'+i,name:n.events.onRequest,actionSequence:[{type:'action',name:actions[i].name}]}));
const server={meta:{id:'gcs-server-uploads',name:'GCS-Server-Uploads',version:'1.0.0'},activeStageId:bp,stage:{grid},objects:[],actions:[],tasks:[],variables:[],stages:[{id:bp,name:'Uploads',type:'blueprint',grid,objects:nodes.map(n=>n.toDTO()),actions,tasks,variables:[],features:[{id:'server-uploads',name:'Dateien prüfen und zuordnen',blueprintTaskNames:tasks.map(t=>t.name)}]}]};projectStore.setProject(server);fs.writeFileSync(folder+'GCS-Server-Uploads.json',JSON.stringify(server,null,2));console.log('Upload-Projekte und Integrationen erzeugt.');
