import fs from 'node:fs';
import {AgentController} from '../src/services/AgentController';
import {projectStore} from '../src/services/ProjectStore';
import {coreStore} from '../src/services/registry/CoreStore';
import {SchemaMigrator} from '../src/services/SchemaMigrator';
const file='game-server/public/projects/GCS-CMS-Anmeldung.json';
if(fs.existsSync(file)&&!process.argv.includes('--replace-generated'))throw Error('Anmeldeprojekt existiert bereits.');
const grid={cols:64,rows:40,cellSize:18,visible:false,backgroundColor:'#122b39'};
const project:any={meta:{id:'gcs-cms-login',name:'GCS-CMS-Anmeldung',version:'1.0.0'},stage:{grid},stages:[],objects:[],actions:[],tasks:[],variables:[],activeStageId:'stage_main'};
projectStore.setProject(project);coreStore.setProject(project);const agent=AgentController.getInstance();agent.setProject(project);
const bp='stage_blueprint',main='stage_main';agent.createStage(bp,'Anmeldeablauf','blueprint',{grid});agent.createStage(main,'Verwaltung anmelden','main',{grid,startAnimation:'none'});coreStore.setActiveStageId(main);
agent.addVariable('Busy','integer',0,'global');
agent.addVariable('EingabenGueltig','boolean',false,'global');
const label=(name:string,y:number,text:string,size=20)=>agent.createLabel(main,name,12,y,text,{width:42,height:2,fontSize:size,color:'#edf7f4',style:{backgroundColor:'transparent',borderWidth:0}});
label('Titel',3,'VERWALTUNG ANMELDEN',28);label('Hinweis',6,'Dein persönlicher Zugang zur Verwaltung',17);
label('BenutzernameLabel',10,'Benutzername');label('PasswortLabel',16,'Passwort');
for(const [name,y,hint,type,auto,max]of [['username',12,'Benutzername','text','username',80],['password',18,'Passwort','password','current-password',200]]as any[])agent.addObject(main,{className:'TEdit',name,x:12,y,width:40,height:3,text:'',placeholder:hint,inputType:type,autocomplete:auto,maxLength:max});
agent.addObject(main,{className:'TButton',name:'Anmelden',x:12,y:23,width:40,height:3,text:'Anmelden',style:{backgroundColor:'#285464',color:'#fff',borderColor:'#76c6bb',borderWidth:1,borderRadius:9,fontSize:20}});
label('Status',28,'Bitte Benutzername und Passwort eingeben.',17);
agent.addObject(main,{className:'TLink',name:'VerwaltungOeffnen',x:12,y:32,width:40,height:2,text:'Verwaltung öffnen →',url:'/admin',target:'_self',visible:false});
agent.addObject(main,{className:'TLink',name:'SpielerEinwahl',x:12,y:36,width:40,height:2,text:'Zur Spieler-Einwahl',url:'/',target:'_self'});
const task=(name:string)=>agent.createTask(bp,name,name);
const action=(task:string,type:any,name:string,params:any)=>agent.addAction(task,type,name,params);
const property=(task:string,name:string,changes:any)=>action(task,'property',name,{changes});
['Anmeldung_Starten','Eingaben_Pruefen','Anmeldung_Anfordern','Anmeldung_Auswerten','Anmeldung_Erfolgreich','Anmeldung_Abgelehnt','Eingaben_Unvollstaendig','Verwaltung_Oeffnen'].forEach(task);
agent.addBranch('Anmeldung_Starten','Busy','==',0,b=>b.addTaskCall('Eingaben_Pruefen'));
action('Eingaben_Pruefen','calculate','Act_Pflichtfelder_Pruefen',{formula:'username.text.length > 0 && password.text.length > 0',resultVariable:'EingabenGueltig'});
agent.addBranch('Eingaben_Pruefen','EingabenGueltig','==',true,b=>b.addTaskCall('Anmeldung_Anfordern'),b=>b.addTaskCall('Eingaben_Unvollstaendig'));
property('Eingaben_Unvollstaendig','Act_Pflichtfeldhinweis_Anzeigen',{'Status.text':'Bitte Benutzername und Passwort ausfüllen.'});
property('Anmeldung_Anfordern','Act_Anmeldung_Als_Laufend_Markieren',{Busy:1,'Status.text':'Zugang wird geprüft …','VerwaltungOeffnen.visible':false});
action('Anmeldung_Anfordern','http','Act_Verwaltungszugang_Anfragen',{url:'/api/cms/admin-login',method:'POST',body:{username:'${username.text}',password:'${password.text}'},resultVariable:'Antwort'});
agent.addTaskCall('Anmeldung_Anfordern','Anmeldung_Auswerten');
property('Anmeldung_Auswerten','Act_Passwort_Leeren_Und_Eingabe_Freigeben',{Busy:0,'password.text':''});
agent.addBranch('Anmeldung_Auswerten','Antwort.ok','==',true,b=>b.addTaskCall('Anmeldung_Erfolgreich'),b=>b.addTaskCall('Anmeldung_Abgelehnt'));
property('Anmeldung_Erfolgreich','Act_Erfolg_Und_Verwaltungslink_Anzeigen',{'Status.text':'${Antwort.message}','VerwaltungOeffnen.visible':true});
property('Anmeldung_Abgelehnt','Act_Anmeldefehler_Anzeigen',{'Status.text':'Anmeldung nicht möglich. Zugang und Verbindung prüfen.'});
agent.addBranch('Anmeldung_Abgelehnt','Antwort.ok','==',false,b=>{b.addTaskCall('Serverfehler_Anzeigen')});
task('Serverfehler_Anzeigen');property('Serverfehler_Anzeigen','Act_Servermeldung_Anzeigen',{'Status.text':'${Antwort.message}'});
action('Verwaltung_Oeffnen','call_method','Act_Verwaltung_Im_Selben_Fenster_Oeffnen',{target:'VerwaltungOeffnen',method:'open',params:[]});
agent.connectEvent(main,'Anmelden','onClick','Anmeldung_Starten');agent.connectEvent(main,'password','onEnter','Anmeldung_Starten');agent.connectEvent(main,'VerwaltungOeffnen','onClick','Verwaltung_Oeffnen');
for(const stage of project.stages)for(const obj of stage.objects)agent.setProperty(stage.id,obj.name,'id',stage.id+'_'+obj.name);
for(const v of project.variables)projectStore.dispatch({type:'SET_PROPERTY',target:v,path:'id',value:'login_var_'+v.name});
agent.createFeature(main,{id:'admin-login',name:'Bei der Verwaltung anmelden',description:'Eingaben prüfen, Zugang anfordern und Verwaltung öffnen',blueprintTaskNames:project.stages[0].tasks.map((t:any)=>t.name),userStoryIds:['admin-login-story']});
projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'userStories',value:{userStories:[{id:'admin-login-story',projectId:'gcs-cms-login',title:'Mit meinem Verwaltungszugang anmelden',description:'Eingaben prüfen → Server anfragen → Rückmeldung anzeigen → Verwaltung öffnen',status:'completed',priority:'high',featureId:'admin-login',relatedStages:[main],relatedComponents:['Anmelden'],plannedComponent:{name:'Anmelden',type:'TButton'},plannedEvent:'onClick',plannedTask:'Anmeldung_Starten',acceptanceCriteria:['Passwort verdeckt eingeben.','Fehler sichtbar anzeigen.','Verwaltung erst nach erfolgreicher Anmeldung öffnen.']}]}});
projectStore.dispatch({type:'SET_PROPERTY',target:project.stages[0],path:'variables',value:project.variables});projectStore.dispatch({type:'SET_PROPERTY',target:project,path:'variables',value:[]});SchemaMigrator.assignMissingIds(project);
fs.writeFileSync(file,JSON.stringify(project,null,2));
// Server flow uses the same registered components, with a separate guarded session step.
const server:any=JSON.parse(fs.readFileSync('game-server/public/projects/GCS-Server-Anmeldung.json','utf8'));
server.meta={id:'gcs-server-admin-login',name:'GCS-Server-Verwaltungsanmeldung',version:'1.0.0'};
const stage=server.stages[0],nodes=stage.objects;stage.name='Server · Verwaltungsanmeldung';
nodes[0].endpointPath='/api/cms/admin-login';nodes[1].validationRule='Benutzername und Passwort';nodes[1].failureMessage='Bitte Benutzername und Passwort ausfüllen.';
nodes[2].authenticationMode='Verwaltungspasswort';nodes[2].permissionBoundary='Aktive Person und Verwaltungszuständigkeit erforderlich';nodes[2].failureMessage='Anmeldung nicht möglich.';nodes[2].name='VerwaltungszugangPruefen';
nodes[3].successMessage='Angemeldet. Du kannst die Verwaltung öffnen.';nodes[3].y=24;
nodes.push({id:'admin_session_component',className:'TServerSession',name:'VerwaltungssitzungErstellen',x:2,y:18,width:12,height:3,scope:'global',isService:true,isHiddenInRun:true,executionSide:'server',sessionPolicy:'HttpOnly; SameSite=Strict; 30 Minuten'});
stage.actions[1].target=nodes[2].name;stage.actions[1].name='Act_Verwaltungszugang_Pruefen';
stage.actions.push({id:'admin_session_action',name:'Act_Verwaltungssitzung_Erstellen',type:'call_method',target:nodes[4].name,method:'execute',params:[]});
const t=stage.tasks[0];t.name='Server_Verwaltungsanmeldung_Verarbeiten';t.description='Eingaben prüfen → Zugang prüfen → bei Erfolg Sitzung erstellen → Response senden';nodes[0].events.onRequest=t.name;
t.actionSequence[1].then=[{type:'action',name:stage.actions[1].name},{type:'condition',name:'Ist der Verwaltungszugang gültig?',condition:{variable:'authenticated',operator:'==',value:true},then:[{type:'action',name:'Act_Verwaltungssitzung_Erstellen'}],else:[]}];
stage.features=[{id:'admin-server-login',name:'Verwaltungsanmeldung auf dem Server',description:t.description,blueprintTaskNames:[t.name],userStoryIds:['admin-server-story']}];server.userStories={userStories:[{id:'admin-server-story',projectId:server.meta.id,title:'Verwaltungszugang prüfen und Sitzung bereitstellen',description:t.description,featureId:'admin-server-login',status:'completed',priority:'high',plannedComponent:{name:nodes[0].name,type:'TServerEndpoint'},plannedEvent:'onRequest',plannedTask:t.name,relatedStages:[stage.id],relatedComponents:[nodes[0].name]}]};
const serverFile='game-server/public/projects/GCS-Server-Verwaltungsanmeldung.json';if(fs.existsSync(serverFile)&&!process.argv.includes('--replace-generated'))throw Error('Serverprojekt existiert bereits.');
projectStore.setProject(server);fs.writeFileSync(serverFile,JSON.stringify(server,null,2));console.log(file,serverFile);
